name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, '*']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install test dependencies
        run: |
          sudo apt install xz-utils brotli

      - name: Set up WASI-SDK
        run: |
          npm run setup-wasi-sdk

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Build & test
        run: make && npm run test
        env:
          # Legacy provider required for old webpack version in new Node releases:
          NODE_OPTIONS: ${{ matrix.node-version != '16.x' && '--openssl-legacy-provider' || '' }}